### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mfonolleda** [diogob/user_notifier#10]
Hi,

I was wondering whether it is possible to create different templates for each language, assuming the app is using i18n.

Thanks!

MF

**Comment by diogob** [comment]
Yes, this should work as ActiveMailer will render according to the locale configured for the notification as you can see [in this line](https://github.com/diogob/user_notifier/blob/master/app/mailers/user_notifier/mailer.rb#L7).

Each notification can be created with a custom locale, and it defaults to the current value of `I18n.locale` as you can see in [this line](https://github.com/diogob/user_notifier/blob/master/lib/user_notifier/models/base.rb#L10).
